apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replica }}
  selector:
    matchLabels:
      {{- include "appdep.labels" . | nindent 8 }} ### <------ we will copy this and put it inside the service file 
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: {{ .Values.app.con1 }}
        image: {{ .Values.app.image }}
        ports:
        - containerPort: {{ .Values.app.port }}
